### ISSUE TITLE
ページの組み上げ

### ISSUE THREAD

**Issue by ltoppyl** [nglcobdai/typing-game#4]
## ✨ 概要

- 作成したコンポーネントを組み上げ、ゲーム開始からゲーム終了(再スタート) までの一連の流れがつながる
- 以下のタスクの完了を待つ
  - #1 
  - #2 
  - #3 

## 🔥 ゴール

- ゲーム開始からゲーム終了(再スタート) までの一連の流れを体験できる

**Comment by nglcobdai** [comment]
@ltoppyl 
このIssueの前に
#13 
#14 
を先に解決したいと思ってるけど、どう思う？

**Comment by ltoppyl** [comment]
@nglcobdai 
#13 とかは先にやった方がページの繋ぎ込みはしやすいのかなー！？

クリティカルな依存関係は無さそうだから、決めの問題っぽいなー

**Comment by nglcobdai** [comment]
@ltoppyl 
了解、なら #13 は先にやろうと思う

この時のbranchの切り方2つあって、迷っていて
- developから派生→develop宛にPR→developから #4 用branchにマージ
- #4 用branchから派生→ #13 の修正を #4 用branch宛にPR
どちらが自然？ 

なお、#4 用branchではまだ1回もコミットしていない

**Comment by ltoppyl** [comment]
@nglcobdai 
どっちの運用もある

後者を使う場合は、特定の機能を作るのに PR を分けたくて、全 PR が揃うまで機能が中途半端だから develop には入れたくない、みたいな時に使うことが多いかな

それでいうと、今回はそんなことはなさそうな気がしているから、ぼくなら前者でやりそう

後者のだとブランチの運用は以下みたいな感じが好み
develop ← topic/###
topic/### ← feature/##a
topic/### ← feature/##b
…
topic/### は必要な機能が全部出来たら、そのまま develop に Merge(ここで新しいことはしない)

**Comment by ltoppyl** [comment]
#13 は完了しないと、ゲームの一連の流れに支障ありそう(ゲームが終了しない気がした)
#14 も完了しないと、ゲームの一連の流れに支障ある！？(あるなら、#4 より先にやっても良いかも)

#4 も割と大きいタスクにしてしまってるから、最初はゲーム開始だけ、次にコードを打つ所まで etc… #4 を親タスクにして、小さくさらに分割とかしても全然よいよー、
そこらへんは、よしなにやって欲しい

**Comment by nglcobdai** [comment]
@ltoppyl 
> 後者を使う場合は、特定の機能を作るのに PR を分けたくて、全 PR が揃うまで機能が中途半端だから develop には入れたくない、みたいな時に使うことが多いかな
それでいうと、今回はそんなことはなさそうな気がしているから、ぼくなら前者でやりそう

確かに、中途半端って感じではないから、
develop -> feature/13
develop <- feature/13
develop -> feature/4
develop <- feature/4
にすることにします！

> https://github.com/nglcobdai/typing-game/issues/14 も完了しないと、ゲームの一連の流れに支障ある！？(あるなら、https://github.com/nglcobdai/typing-game/issues/4 より先にやっても良いかも)

#14 完了しなくても、ゲーム自体は成り立つから、#4 終わった後にやります！
